### PR TITLE
Feat/fix pages tree

### PR DESCRIPTION
**Pull request by ValeriyaKa**
@coderabbitai review

## Summary by CodeRabbit

- **New Features**
	- Introduced new SCSS styles for enhanced list item presentation and interaction.
	- Updated the `PagesTree` component to improve type safety with TypeScript interfaces.
	- Added a new test suite for the `PagesTree` component to ensure expected functionality.

- **Bug Fixes**
	- Improved handling of undefined values in the `PagesTree` component.

- **Style**
	- Enhanced styling and layout for the `.project-card` component with updated class naming conventions and cross-browser compatibility.
	- Minor formatting adjustments in the `App` component.

- **Chores**
	- Removed unnecessary code and streamlined the `ProjectCard` component structure.
	- Updated TypeScript configuration by removing Vitest global types.
	- Deleted outdated SCSS file for the `PagesTree` component.

### CODE REVIEW

**Comment by ValeriyaKa** [comment]
https://github.com/coderabbitai review

**Comment by ValeriyaKa** [comment]
@coderabbitai review

**Comment by ValeriyaKa** [comment]
@coderabbitai review

**Review by poplopok — COMMENTED** [review]
good

**Comment by ValeriyaKa** [comment]
Ярик не ругайся и не мерджи, тесты ещё не сделала

**Comment by ValeriyaKa** [comment]
@coderabbitai review

**Comment by ValeriyaKa** [comment]
@coderabbitai review

**Pull request closed without merging**
